// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using spydle_api.Data;

#nullable disable

namespace spydle_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260411155237_EyeAndSkinColor")]
    partial class EyeAndSkinColor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("spydle_api.Models.Case", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<int[]>("IncludedCharacters")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("RngSeed")
                        .HasColumnType("integer");

                    b.Property<int>("SpyCharacterCode")
                        .HasColumnType("integer");

                    b.HasKey("Date");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("spydle_api.Models.Character", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Code");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("spydle_api.Models.CharacterEyeColor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<byte>("Blue")
                        .HasColumnType("smallint");

                    b.Property<byte>("Green")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Red")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("CharacterEyeColors");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Blue = (byte)30,
                            Green = (byte)58,
                            Name = "Brown",
                            Red = (byte)97
                        },
                        new
                        {
                            Id = 1,
                            Blue = (byte)209,
                            Green = (byte)87,
                            Name = "Blue",
                            Red = (byte)46
                        },
                        new
                        {
                            Id = 2,
                            Blue = (byte)59,
                            Green = (byte)212,
                            Name = "Green",
                            Red = (byte)125
                        },
                        new
                        {
                            Id = 3,
                            Blue = (byte)199,
                            Green = (byte)166,
                            Name = "Grey",
                            Red = (byte)155
                        });
                });

            modelBuilder.Entity("spydle_api.Models.CharacterSkinColor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<byte>("Blue")
                        .HasColumnType("smallint");

                    b.Property<byte>("Green")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Red")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("CharacterSkinColors");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Blue = (byte)214,
                            Green = (byte)214,
                            Name = "Cyan",
                            Red = (byte)41
                        },
                        new
                        {
                            Id = 1,
                            Blue = (byte)15,
                            Green = (byte)217,
                            Name = "Yellow",
                            Red = (byte)255
                        },
                        new
                        {
                            Id = 2,
                            Blue = (byte)73,
                            Green = (byte)41,
                            Name = "Red",
                            Red = (byte)214
                        },
                        new
                        {
                            Id = 3,
                            Blue = (byte)41,
                            Green = (byte)214,
                            Name = "Green",
                            Red = (byte)52
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
