// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using spydle_api.Data;

#nullable disable

namespace spydle_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502164612_InterrogationToInterrogations")]
    partial class InterrogationToInterrogations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("spydle_api.Entities.Interrogation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FoundMatchingTrait")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("Suspects")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CaseDate");

                    b.HasIndex("UserId");

                    b.ToTable("Interrogations", (string)null);
                });

            modelBuilder.Entity("spydle_api.Models.Case", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<int[]>("IncludedCharacters")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("RngSeed")
                        .HasColumnType("integer");

                    b.Property<int>("SpyCharacterCode")
                        .HasColumnType("integer");

                    b.HasKey("Date");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("spydle_api.Models.Character", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Code");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Code = 0,
                            IsActive = true
                        },
                        new
                        {
                            Code = 1,
                            IsActive = true
                        },
                        new
                        {
                            Code = 2,
                            IsActive = true
                        },
                        new
                        {
                            Code = 3,
                            IsActive = true
                        },
                        new
                        {
                            Code = 4,
                            IsActive = true
                        },
                        new
                        {
                            Code = 5,
                            IsActive = true
                        },
                        new
                        {
                            Code = 6,
                            IsActive = true
                        },
                        new
                        {
                            Code = 7,
                            IsActive = true
                        },
                        new
                        {
                            Code = 8,
                            IsActive = true
                        },
                        new
                        {
                            Code = 9,
                            IsActive = true
                        },
                        new
                        {
                            Code = 10,
                            IsActive = true
                        },
                        new
                        {
                            Code = 11,
                            IsActive = true
                        },
                        new
                        {
                            Code = 12,
                            IsActive = true
                        },
                        new
                        {
                            Code = 13,
                            IsActive = true
                        },
                        new
                        {
                            Code = 14,
                            IsActive = true
                        },
                        new
                        {
                            Code = 15,
                            IsActive = true
                        },
                        new
                        {
                            Code = 16,
                            IsActive = true
                        },
                        new
                        {
                            Code = 17,
                            IsActive = true
                        },
                        new
                        {
                            Code = 18,
                            IsActive = true
                        },
                        new
                        {
                            Code = 19,
                            IsActive = true
                        },
                        new
                        {
                            Code = 20,
                            IsActive = true
                        },
                        new
                        {
                            Code = 21,
                            IsActive = true
                        },
                        new
                        {
                            Code = 22,
                            IsActive = true
                        },
                        new
                        {
                            Code = 23,
                            IsActive = true
                        },
                        new
                        {
                            Code = 24,
                            IsActive = true
                        },
                        new
                        {
                            Code = 25,
                            IsActive = true
                        },
                        new
                        {
                            Code = 26,
                            IsActive = true
                        },
                        new
                        {
                            Code = 27,
                            IsActive = true
                        },
                        new
                        {
                            Code = 28,
                            IsActive = true
                        },
                        new
                        {
                            Code = 29,
                            IsActive = true
                        },
                        new
                        {
                            Code = 30,
                            IsActive = true
                        },
                        new
                        {
                            Code = 31,
                            IsActive = true
                        },
                        new
                        {
                            Code = 32,
                            IsActive = true
                        },
                        new
                        {
                            Code = 33,
                            IsActive = true
                        },
                        new
                        {
                            Code = 34,
                            IsActive = true
                        },
                        new
                        {
                            Code = 35,
                            IsActive = true
                        },
                        new
                        {
                            Code = 36,
                            IsActive = true
                        },
                        new
                        {
                            Code = 37,
                            IsActive = true
                        },
                        new
                        {
                            Code = 38,
                            IsActive = true
                        },
                        new
                        {
                            Code = 39,
                            IsActive = true
                        },
                        new
                        {
                            Code = 40,
                            IsActive = true
                        },
                        new
                        {
                            Code = 41,
                            IsActive = true
                        },
                        new
                        {
                            Code = 42,
                            IsActive = true
                        },
                        new
                        {
                            Code = 43,
                            IsActive = true
                        },
                        new
                        {
                            Code = 44,
                            IsActive = true
                        },
                        new
                        {
                            Code = 45,
                            IsActive = true
                        },
                        new
                        {
                            Code = 46,
                            IsActive = true
                        },
                        new
                        {
                            Code = 47,
                            IsActive = true
                        },
                        new
                        {
                            Code = 48,
                            IsActive = true
                        },
                        new
                        {
                            Code = 49,
                            IsActive = true
                        },
                        new
                        {
                            Code = 50,
                            IsActive = true
                        },
                        new
                        {
                            Code = 51,
                            IsActive = true
                        },
                        new
                        {
                            Code = 52,
                            IsActive = true
                        },
                        new
                        {
                            Code = 53,
                            IsActive = true
                        },
                        new
                        {
                            Code = 54,
                            IsActive = true
                        },
                        new
                        {
                            Code = 55,
                            IsActive = true
                        },
                        new
                        {
                            Code = 56,
                            IsActive = true
                        },
                        new
                        {
                            Code = 57,
                            IsActive = true
                        },
                        new
                        {
                            Code = 58,
                            IsActive = true
                        },
                        new
                        {
                            Code = 59,
                            IsActive = true
                        },
                        new
                        {
                            Code = 60,
                            IsActive = true
                        },
                        new
                        {
                            Code = 61,
                            IsActive = true
                        },
                        new
                        {
                            Code = 62,
                            IsActive = true
                        },
                        new
                        {
                            Code = 63,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("spydle_api.Models.CharacterEyeColor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<byte>("Blue")
                        .HasColumnType("smallint");

                    b.Property<byte>("Green")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Red")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("CharacterEyeColors");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Blue = (byte)30,
                            Green = (byte)58,
                            Name = "Brown",
                            Red = (byte)97
                        },
                        new
                        {
                            Id = 1,
                            Blue = (byte)209,
                            Green = (byte)87,
                            Name = "Blue",
                            Red = (byte)46
                        },
                        new
                        {
                            Id = 2,
                            Blue = (byte)59,
                            Green = (byte)212,
                            Name = "Green",
                            Red = (byte)125
                        },
                        new
                        {
                            Id = 3,
                            Blue = (byte)199,
                            Green = (byte)166,
                            Name = "Grey",
                            Red = (byte)155
                        });
                });

            modelBuilder.Entity("spydle_api.Models.CharacterSkinColor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<byte>("Blue")
                        .HasColumnType("smallint");

                    b.Property<byte>("Green")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Red")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("CharacterSkinColors");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Blue = (byte)214,
                            Green = (byte)214,
                            Name = "Cyan",
                            Red = (byte)41
                        },
                        new
                        {
                            Id = 1,
                            Blue = (byte)15,
                            Green = (byte)217,
                            Name = "Yellow",
                            Red = (byte)255
                        },
                        new
                        {
                            Id = 2,
                            Blue = (byte)73,
                            Green = (byte)41,
                            Name = "Red",
                            Red = (byte)214
                        },
                        new
                        {
                            Id = 3,
                            Blue = (byte)41,
                            Green = (byte)214,
                            Name = "Green",
                            Red = (byte)52
                        });
                });

            modelBuilder.Entity("spydle_api.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("spydle_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("spydle_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("spydle_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("spydle_api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("spydle_api.Entities.Interrogation", b =>
                {
                    b.HasOne("spydle_api.Models.Case", "Case")
                        .WithMany("Interrogations")
                        .HasForeignKey("CaseDate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("spydle_api.Models.User", "User")
                        .WithMany("Interrogations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("spydle_api.Models.Case", b =>
                {
                    b.Navigation("Interrogations");
                });

            modelBuilder.Entity("spydle_api.Models.User", b =>
                {
                    b.Navigation("Interrogations");
                });
#pragma warning restore 612, 618
        }
    }
}
