// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using spydle_api.Data;

#nullable disable

namespace spydle_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410175518_Characters")]
    partial class Characters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("spydle_api.Models.Case", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CharacterCode")
                        .HasColumnType("integer");

                    b.Property<int>("RngSeed")
                        .HasColumnType("integer");

                    b.HasKey("Date");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("spydle_api.Models.Character", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Code");

                    b.ToTable("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
